version: '3.4'

services:
  layerensembles:
    image: layerensembles
    build:
      context: /home/kaisar/EuCanImage/Coding/LayerEnsembles
      dockerfile: /home/kaisar/EuCanImage/Coding/LayerEnsembles/Dockerfile